export const BackendRoutes = {
  ADD_SKILL: "addSkill",
  ADD_TASK: "addTask",
  COMPLETE_TASK: "completeTask",
  CREATE_USER: "createUser",
  DELETE_FILE: "deleteFile",
  DELETE_SKILL: "deleteSkill",
  GET_SKILLS: "getSkills",
  LOGIN: "login",
  LOGOUT: "logout",
  REFRESH: "refresh",
  REPLACE_FILE: "replaceFile",
  SINGLE_SKILL: "singleSkill",
  SKILL: "skill",
  TASKS: "tasks",
  UPDATE_SKILL: "updateSkill",
  UPDATE_TASK: "updateTask",
  UPDATE_USER_LEVEL: "updateUserLevel",
  UPDATE_USER: "updateUser",
  UPLOAD: "upload",
  USER: "user",
  USERS: "users",
};
