export const BackendRoutes = {
  LOGIN: "login",
  REFRESH: "refresh",
  USER: "user",
  USERS: "users",
  LOGOUT: "logout",
  UPDATE_USER: "updateUser",
  UPLOAD: "upload",
  DELETE_FILE: "deleteFile",
  REPLACE_FILE: "replaceFile",
  ADD_SKILL: "addSkill",
  GET_SKILLS: "getSkills",
  SKILL: "skill",
  ADD_TASK: "addTask",
  TASKS: "tasks",
  UPDATE_TASK: "updateTask",
  DELETE_SKILL: "deleteSkill",
};
