export const UIRoutes = {
  ROOT: "/",
  ABOUT: "about",
  ADD_SKILL: "add-skill",
  HOME: "home",
  LOGIN: "login",
  MODIFY_SKILL_ID: "modify-skill/:skillId",
  MODIFY_SKILL: "modify-skill",
  PROFILE: "profile",
  REGISTER: "register",
  SKILL_DETAIL: "skill/:skillId",
  SKILL_TASKS: "skill/:skillId/tasks",
  SKILL: "skill",
  TASK_INTAKE_WIZARD: "task-intake-wizard",
  TASKS: "tasks",
};
